# VERSION 0.1
# DOCKER-VERSION  1.7.0
# AUTHOR:         
# DESCRIPTION:    Template for a CAF Raspberry Pi app (armv7)
# TO_BUILD:       docker build --rm -t localhost.localdomain:5000/<appName>:<etag> .
# TO_RUN:         cafjs device ...
#

FROM gcr.io/cafjs-k8/root-rpi2armhf

ENTRYPOINT ["node"]

CMD [ "./index.js" ]
